library(devtools)                                          
install_github('stan-dev/rstan/rstan/rstan', ref='develop')
install.packages("dplyr")
install.packages("tikzDevice")
install.packages("tidyverse")
install.packages("scales")
install.packages("splines")
install.packages("lubridate")
install.packages("loo")
install.packages("tidyr")
install.packages("reshape2")
install.packages("matrixStats")
install.packages("MASS")
install.packages("timeDate")
install.packages("ggplot2")
install.packages("rstan")
install.packages("stringr")
install.packages("knitr")

